# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-22 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('sname', models.CharField(max_length=64)),
                ('sclass', models.CharField(max_length=64)),
                ('saddr', models.CharField(max_length=100)),
            ],
        ),
    ]
