# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-03 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_student_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='eno',
            field=models.CharField(max_length=30),
        ),
    ]
