# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-03 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_auto_20200403_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='eno',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
