# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-06 05:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_studentinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
